# CodeBuild buildspec to build Lambdas and package project
#
# Required environment variables:
#  ARTIFACTS_BUCKET     = S3 bucket name/path for the artifacts upload
#  ARTIFACTS_KMS_ID     = KMS key ID used for artifacts bucket

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install awscli aws-sam-cli
  build:
    commands:
      - sam build --template-file template.yaml
      - aws cloudformation package --template-file template.yaml --s3-bucket $ARTIFACTS_BUCKET --kms-key-id $ARTIFACTS_KMS_ID --output-template-file output.yml

artifacts:
  files:
    - output.yml