# CodeBuild buildspec to build Lambdas and package project
#
# Required environment variables:
#  ARTIFACTS_BUCKET                 = S3 bucket name/path for the artifacts upload
#  ARTIFACTS_KMS_ID                 = KMS key ID used for artifacts bucket
#  REPOSITORY_URI_INIT_TABLE        = Repo for init_table images
#  REPOSITORY_URI_SYNC_TABLE        = Repo for sync_table images
#  AWS_ACCOUNT_ID                   = Account ID of AWS

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install awscli aws-sam-cli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Tagging init_table for production...
      - docker pull $REPOSITORY_URI_INIT_TABLE:stg
      - docker tag $REPOSITORY_URI_INIT_TABLE:stg $REPOSITORY_URI_INIT_TABLE:prod
      - echo Tagging sync_table for production...
      - docker pull $REPOSITORY_URI_SYNC_TABLE:stg
      - docker tag $REPOSITORY_URI_SYNC_TABLE:stg $REPOSITORY_URI_SYNC_TABLE:prod      
  post_build:
    commands:
      - echo Pushing Docker images for init_table...
      - docker push $REPOSITORY_URI_INIT_TABLE:prod
      - echo Pushing Docker images for sync_table...
      - docker push $REPOSITORY_URI_SYNC_TABLE:prod

artifacts:
  files:
    - output.yml