# CodeBuild buildspec to build Lambdas and package project
#
# Required environment variables:
#  ARTIFACTS_BUCKET                 = S3 bucket name/path for the artifacts upload
#  ARTIFACTS_KMS_ID                 = KMS key ID used for artifacts bucket
#  REPOSITORY_URI_INIT_TABLE        = Repo for init_table images
#  REPOSITORY_URI_SYNC_TABLE        = Repo for sync_table images
#  AWS_ACCOUNT_ID                   = Account ID of AWS

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install awscli aws-sam-cli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Starting Docker build for init_table...
      - docker build -t $REPOSITORY_URI_INIT_TABLE:latest $CODEBUILD_SRC_DIR/init_table/
      - docker tag $REPOSITORY_URI_INIT_TABLE:latest $REPOSITORY_URI_INIT_TABLE:$IMAGE_TAG
      - docker tag $REPOSITORY_URI_INIT_TABLE:latest $REPOSITORY_URI_INIT_TABLE:stg
      - echo Starting Docker build for sync_table...
      - docker build -t $REPOSITORY_URI_SYNC_TABLE:latest $CODEBUILD_SRC_DIR/sync_table/
      - docker tag $REPOSITORY_URI_SYNC_TABLE:latest $REPOSITORY_URI_SYNC_TABLE:$IMAGE_TAG
      - docker tag $REPOSITORY_URI_SYNC_TABLE:latest $REPOSITORY_URI_SYNC_TABLE:stg
      - echo Starting SAM build...
      - sam build --template-file template.yaml
      - sam package --s3-bucket $ARTIFACTS_BUCKET --kms-key-id $ARTIFACTS_KMS_ID --output-template-file output.yml

  post_build:
    commands:
      - echo Pushing Docker images for init_table...
      - docker push $REPOSITORY_URI_INIT_TABLE:latest
      - docker push $REPOSITORY_URI_INIT_TABLE:stg
      - docker push $REPOSITORY_URI_INIT_TABLE:$IMAGE_TAG
      - echo Pushing Docker images for sync_table...
      - docker push $REPOSITORY_URI_SYNC_TABLE:latest
      - docker push $REPOSITORY_URI_SYNC_TABLE:stg
      - docker push $REPOSITORY_URI_SYNC_TABLE:$IMAGE_TAG

artifacts:
  files:
    - output.yml